version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
    open-pull-requests-limit: 10
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
    groups:
      angular:
        patterns:
          - '@angular/*'
    open-pull-requests-limit: 10
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'develop'
