services:
  nginx:
    image: nginx:1.28.0-alpine-slim
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '80'
      - '443'
    healthcheck:
      test: service nginx status || exit 1
      start_period: 10s
    restart: always
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/artemis-performance-test0.artemis.cit.tum.de80:/etc/nginx/sites-enabled/artemis-performance-test0.artemis.cit.tum.de80:ro
      - ./config/nginx/artemis-performance-test0.artemis.cit.tum.de443:/etc/nginx/sites-enabled/artemis-performance-test0.artemis.cit.tum.de443:ro
      - type: bind
        source: '/var/lib/rbg-cert/live/host:f:artemis-performance-test0.artemis.cit.tum.de.fullchain.pem'
        target: '/certs/fullchain.pem'
      - type: bind
        source: '/var/lib/rbg-cert/live/host:f:artemis-performance-test0.artemis.cit.tum.de.privkey.pem'
        target: '/certs/privkey.pem'
