export enum RequestType {
  TOTAL = 'TOTAL',
  AUTHENTICATION = 'AUTHENTICATION',
  GET_STUDENT_EXAM = 'GET_STUDENT_EXAM',
  START_STUDENT_EXAM = 'START_STUDENT_EXAM',
  SUBMIT_EXERCISE = 'SUBMIT_EXERCISE',
  SUBMIT_STUDENT_EXAM = 'SUBMIT_STUDENT_EXAM',
  CLONE = 'CLONE',
  PUSH = 'PUSH',
  MISC = 'MISC',
}
