# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: artemis-benchmarking
services:
  app:
    image: artemis-benchmarking
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/benchmarking
      - SPRING_DATASOURCE_USERNAME=benchmarking
      - SPRING_DATASOURCE_PASSWORD=benchmarking
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgres:5432/benchmarking
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    extends:
      file: ./postgresql.yml
      service: postgres
