- hosts: artemis-performance-test0.artemis.cit.tum.de
  become: true
  gather_facts: false

  vars:
    - benchmarking_root_dir: "/opt/artemis-benchmarking"

  tasks:
    - name: Create benchmark app directories.
      file:
        path: "{{ item}}"
        state: directory
        owner: root
        group: root
        mode: "700"
      with_items:
        - "{{ benchmarking_root_dir }}"
        - "{{ benchmarking_root_dir }}/config"

    - name: Ensure benchmarking configuration files are present.
      copy:
        src: "{{ item }}"
        dest: "{{ benchmarking_root_dir }}/config/{{ item }}"
        owner: root
        group: root
        mode: "600"
        force: false
      with_items:
        - "mysql.env"
        - "benchmarking.env"

    - name: Copy benchmarking docker-compose.yml.
      template:
        src: "docker-compose.yml.j2"
        dest: "{{ benchmarking_root_dir }}/docker-compose.yml"
        owner: root
        group: root
        mode: "600"
    - name: Start benchmarking server.
      command: "docker-compose up -d --remove-orphans --force-recreate"
      args:
          chdir: "{{ benchmarking_root_dir }}"
