package de.tum.cit.ase.domain;

public enum RequestType {
    TOTAL,
    AUTHENTICATION,
    GET_STUDENT_EXAM,
    START_STUDENT_EXAM,
    SUBMIT_EXERCISE,
    SUBMIT_STUDENT_EXAM,
    CLONE,
    PUSH,
    PROGRAMMING_EXERCISE_RESULT,
    REPOSITORY_INFO,
    REPOSITORY_FILE,
    REPOSITORY_FILES,
    PLANT_UML,
    MISC,
}
