package de.tum.cit.ase.domain;

public enum RequestType {
    TOTAL,
    AUTHENTICATION,
    GET_STUDENT_EXAM,
    START_STUDENT_EXAM,
    SUBMIT_EXERCISE,
    SUBMIT_STUDENT_EXAM,
    CLONE,
    PUSH,
    PROGRAMMING_EXERCISE_RESULT,
    REPOSITORY_INFO,
    REPOSITORY_FILES,
    MISC,
    SETUP_SSH_KEYS,
    FETCH_PARTICIPATION_VCS_ACCESS_TOKEN,
    CLONE_SSH,
    CLONE_TOKEN,
    CLONE_PASSWORD,
    PUSH_SSH,
    PUSH_TOKEN,
    PUSH_PASSWORD,
}
