# You can enable the CI workflow by uncommenting the following lines.
# This will compile, lint and test the code on every push to the main branch and for pull requests.
# Currently, the CI will fail as there are linting errors in the code.

name: Continuous Integration

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Run Server Tests
        run: ./gradlew test -x webapp jacocoTestReport
      - name: Install Dependencies
        run: npm install
      - name: Run Client Tests
        run: npm test
